<?php
/**
 * @file
 * Code for the GSB Feature Seed Research Library Content Type feature.
 */

include_once 'gsb_feature_seed_research_library_ct.features.inc';

/**
 * Implements hook_form_FORM_ID_alter() for seed research library node edit form.
 */
function gsb_feature_seed_research_library_ct_form_seed_research_project_node_form_alter(&$form, &$form_state) {

  $language = $form['language']['#value'];
 //principal investigator
  $form['field_srl_principal_investigator'][$language][0]['field_person_fac_single_ref']['#states'] = array(
    'visible' => array(
      ':input[name="field_srl_principal_investigator[' . $language . '][0][field_faculty_or_other][' . $language . ']"]' => array(
        array('value' => 'UseEntityReference'),
      ),
    ),
    'required' => array(
      ':input[name="field_srl_principal_investigator[' . $language . '][0][field_faculty_or_other][' . $language . ']"]' => array(
        array('value' => 'UseEntityReference'),
      ),
    ),
  );
  $form['field_srl_principal_investigator'][$language][0]['field_other_name']['#states'] = array(
    'visible' => array(
      ':input[name="field_srl_principal_investigator[' . $language . '][0][field_faculty_or_other][' . $language . ']"]' => array(
        array('value' => 'Other'),
      ),
    ),
    'required' => array(
      ':input[name="field_srl_principal_investigator[' . $language . '][0][field_faculty_or_other][' . $language . ']"]' => array(
        array('value' => 'Other'),
      ),
    ),
  );
  // remove "n/a" as an option for the fac_or_other
  unset($form['field_srl_principal_investigator'][$language][0]['field_faculty_or_other'][$language]['#options']['_none']);

  $form['field_srl_principal_investigator'][$language][0]['field_link_single']['#states'] = array(
    'visible' => array(
      ':input[name="field_srl_principal_investigator[' . $language . '][0][field_faculty_or_other][' . $language . ']"]' => array(
        array('value' => 'Other'),
      ),
    ),
  );

  //co-investigator
  foreach ($form['field_srl_co_investigators'][$language] as $index => $data) {
    if (is_integer($index)) {
      $form['field_srl_co_investigators'][$language][$index]['field_person_fac_single_ref']['#states'] = array(
        'visible' => array(
          ':input[name="field_srl_co_investigators[' . $language . '][' . $index . '][field_faculty_or_other][' . $language . ']"]' => array(
            array('value' => 'UseEntityReference'),
          ),
        ),
      );
      $form['field_srl_co_investigators'][$language][$index]['field_other_name']['#states'] = array(
        'visible' => array(
          ':input[name="field_srl_co_investigators[' . $language . '][' . $index . '][field_faculty_or_other][' . $language . ']"]' => array(
            array('value' => 'Other'),
          ),
        ),
      );
      // remove "n/a" as an option for the fac_or_other
      unset($form['field_srl_co_investigators'][$language][$index]['field_faculty_or_other'][$language]['#options']['_none']);

      $form['field_srl_co_investigators'][$language][$index]['field_link_single']['#states'] = array(
        'visible' => array(
          ':input[name="field_srl_co_investigators[' . $language . '][' . $index . '][field_faculty_or_other][' . $language . ']"]' => array(
            array('value' => 'Other'),
          ),
        ),
      );
    }
  }
  $form['#validate'][] = 'gsb_feature_seed_research_library_ct_form_seed_research_project_node_form_validate';
}

function gsb_feature_seed_research_library_ct_form_seed_research_project_node_form_validate(&$form, &$form_state) {
  $language = $form['language']['#value'];
  $values = $form_state['values'];
  if ($values['field_srl_principal_investigator'][$language][0]['field_faculty_or_other'][$language][0]['value'] == 'UseEntityReference') {
    if (empty($form_state['values']['field_srl_principal_investigator'][ $language ][0]['field_person_fac_single_ref'][$language ][0]['target_id'])) {
      form_set_error('field_srl_principal_investigator][' . $language . '][0][field_person_fac_single_ref', t('Faculty Name is required '));
    }
  }
  if ($values['field_srl_principal_investigator'][$language][0]['field_faculty_or_other'][$language][0]['value'] == 'Other')  {
      if (empty($values['field_srl_principal_investigator'][$language][0]['field_other_name'][$language][0]['value'])) {
      form_set_error('field_srl_principal_investigator][' . $language . '][0][field_other_name', t('Name of Principal investigator is required '));
      }
  }

}
